### ISSUE TITLE
Use Over The Air Activation (OTAA) by default

### ISSUE THREAD

**Issue by frankleonrose** [things-nyc/mapthethings-arduino#2]
Store the assigned device ID to NVRAM (https://learn.adafruit.com/adafruit-feather-m0-bluefruit-le?view=all#at-plus-nvmwrite)

**Comment by frankleonrose** [comment]
This item is now moot. Either you pre-assign ABP keys or OTAA keys or the node gets provisioned by the app.

**Comment by forrestfiller** [comment]
Hooray!

Forrest Filler
