### ISSUE TITLE
Compile error with recent gcc

### ISSUE THREAD

**Issue by terrillmoore** [things-nyc/mapthethings-arduino#4]
Compile failure with latest gcc:
```
Compiling 'MapTheThings-Arduino' for 'Adafruit Feather M0 (Native USB Port)'
 
MapTheThings-Arduino.ino: 4:6: error: previous declaration of 'void debugPrint(const char*)' with 'C++' linkage
   void debugPrint(const char *msg)
 
MapTheThings-Arduino.ino: 18:34: error: conflicts with new declaration with 'C' linkage
   void debugPrint(const char *msg)
Error compiling project sources
Build failed for project 'MapTheThings-Arduino'
```

Since the prototype of debugPrint() is extern "C", the function should be instantiated inside extern "C. In any case, this compiles:
```c++
extern "C" {
void debugPrint(const char *msg) {
  Log.Debug(msg);
  Log.Debug(CR);
  }
}
```
Subsequent discovery: with the Arduino IDE (not Visual Micro), GCC complains about the other functions that were prototyped as extern "C".  I'll submit a patch that covers them all.

**Comment by frankleonrose** [comment]
Thanks for find and fix, @terrillmoore!
